FROM registry.access.redhat.com/ubi8/openjdk-17:latest

USER root
RUN mkdir /app && chown 1001 /app
USER 1001

WORKDIR /app

# Copy Maven wrapper and pom.xml
COPY .mvn/ .mvn/
COPY mvnw pom.xml ./

# Download dependencies
RUN ./mvnw dependency:go-offline -B

# Copy source code
COPY src ./src/

# Run with dev mode enabled
CMD ["./mvnw", "quarkus:dev", "-Dquarkus.http.host=0.0.0.0"]